name: Deploy Node Application

on:
  push: 
    branches:
      - backend-ec2-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file
        run: | 
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}       
      - name: Build docker image
        run: docker build -t revazikukhianidze/nodejs-app .  
      - name: Publish image to docker hub
        run: docker push revazikukhianidze/nodejs-app:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull revazikukhianidze/nodejs-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-backend-container 
      - name: Run docker container
        run: docker run -d -p 3001:3001 --name nodejs-backend-container revazikukhianidze/nodejs-app